services:
  app:
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:
      - "5173:5173"
    working_dir: /app/client
    # volumes:
    #   - .:/app
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app/client
          ignore:
            - node_modules
            - .git
    environment:
      - NODE_ENV=development
    command: bun run dev:docker
  
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app/server
    volumes:
      - ./server:/app/server
      # - node_modules:/app/server/node_modules
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./server
    #       target: /app/server
    #       ignore: 
    #         - node_modules
    #         - .git
    command: ["bun", "run", "dev"]
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
volumes:
  db_data:
  node_modules: